# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "60b4ffe9af147ac94a4a27d3d8cabd4e"
application_url = "https://separately-extending-handbook-smoking.trycloudflare.com"
embedded = true
name = "strox"
handle = "strox"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,read_cart_transforms,write_cart_transforms,read_checkout_branding_settings,write_checkout_branding_settings,read_content,write_content,read_online_store_pages,read_customer_events,write_pixels,read_customer_merge,write_customer_merge,read_customers,write_customers,read_delivery_customizations,write_delivery_customizations,read_discounts,write_discounts,read_draft_orders,write_draft_orders,read_files,write_files,read_fulfillments,write_fulfillments,read_gift_cards,write_gift_cards,read_inventory,write_inventory,read_legal_policies,read_locales,write_locales,read_locations,write_locations,read_marketing_events,write_marketing_events,read_orders,write_orders,read_price_rules,write_price_rules,read_products,write_products,read_publications,write_publications,read_reports,write_reports,read_resource_feedbacks,write_resource_feedbacks,read_script_tags,write_script_tags,read_shipping,write_shipping,read_shopify_payments_payouts,read_shopify_payments_disputes,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://separately-extending-handbook-smoking.trycloudflare.com/auth/callback",
  "https://separately-extending-handbook-smoking.trycloudflare.com/auth/shopify/callback",
  "https://separately-extending-handbook-smoking.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
